# -*- coding: utf-8 -*-
"""Copy of kNN1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txVzT9oarocHYxv8GL-EWRGj1e6gqW4U

# **kth Nearest Neighbour Implementation**
"""

# importing reqd libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# loading data from dataset
data = pd.read_csv('Social_Network_Ads.csv');
data.head()

# Taking input columns
X = data.iloc[:, 2 : 4].values
X.shape

# Storing output column in y
y = data.iloc[:, -1].values
y.shape

# Cross Validation
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# Training data
X_train.shape

X_test.shape

# Standardizing the attributes
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_train

X_test = scaler.fit_transform(X_test)
X_test

"""# M1. k value from sqrt of total number of inputs"""

# Method 1 of k Calculation
np.sqrt(X_train.shape[0])

k = 17

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = k)

# Train the model
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

y_pred.shape

y_test.shape

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

"""# M2. k value by Trial and Error"""

accuracy = []

for i in range (1, 26):
  knn = KNeighborsClassifier(n_neighbors = i)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  accuracy_i = accuracy_score(y_test, y_pred)
  accuracy.append(accuracy_i)

accuracy

plt.plot(range(1, 26), accuracy)

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

"""# Predicting class for Query Point(s)"""

def predict_output():
  age = int(input("Enter the age: "))
  salary = int(input("Enter the salary: "))

  X_new = np.array([[age], [salary]]).reshape(1, 2)
  X_new = scaler.transform(X_new)

  return knn.predict(X_new)[0]

predict_output()